const Map<String, String> nameToCode = {
  'Bitcoin':'BTC',
  'Ethereum':'ETH',
  'EOS':'EOS',
  'XRP':'XRP',
  'Litecoin':'LTC',
  'Bitcoin Cash':'BCH',
  'Stellar':'XLM',
  'Monero':'XMR',
  'TRON':'TRX',
  'Binance Coin':'BNB',
  'United Arab Emirates Dirham':'AED',
  'Argentine Peso':'ARS',
  'Australian Dollar':'AUD',
  'Bulgarian Lev':'BGN',
  'Bolivian Boliviano':'BOB',
  'Brazilian Real':'BRL',
  'Canadian Dollar':'CAD',
  'Swiss Franc':'CHF',
  'Chinese Yuan Renminbi':'CNY',
  'Colombian Peso':'COP',
  'Euro':'EUR',
  'British Pound Sterling':'GBP',
  'Hong Kong Dollar':'HKD',
  'Indian Rupee':'INR',
  'Japanese Yen':'JPY',
  'South Korean Won':'KRW',
  'Mexican Peso':'MXN',
  'Malaysian Ringgit':'MYR',
  'Norwegian Krone':'NOK',
  'New Zealand Dollar':'NZD',
  'Philippine Peso':'PHP',
  'Polish Zloty':'PLN',
  'Romanian Leu':'RON',
  'Russian Ruble':'RUB',
  'Saudi Riyal':'SAR',
  'Swedish Krona':'SEK',
  'Singapore Dollar':'SGD',
  'Thai Baht':'THB',
  'New Taiwan Dollar':'TWD',
  'US Dollar':'USD',
  'Vietnamese Dong':'VND',
  'South African Ran':'ZAR',
};

const Map<String, String> codeToName = {
  'BTC':'Bitcoin',
  'ETH':'Ethereum',
  'EOS':'EOS',
  'XRP':'XRP',
  'LTC':'Litecoin',
  'BCH':'Bitcoin Cash',
  'XLM':'Stellar',
  'XMR':'Monero',
  'TRX':'TRON',
  'BNB':'Binance Coin',
  'AED':'United Arab Emirates Dirham',
  'ARS':'Argentine Peso',
  'AUD':'Australian Dollar',
  'BGN':'Bulgarian Lev',
  'BOB':'Bolivian Boliviano',
  'BRL':'Brazilian Real',
  'CAD':'Canadian Dollar',
  'CHF':'Swiss Franc',
  'CNY':'Chinese Yuan Renminbi',
  'COP':'Colombian Peso',
  'EUR':'Euro',
  'GBP':'British Pound Sterling',
  'HKD':'Hong Kong Dollar',
  'INR':'Indian Rupee',
  'JPY':'Japanese Yen',
  'KRW':'South Korean Won',
  'MXN':'Mexican Peso',
  'MYR':'Malaysian Ringgit',
  'NOK':'Norwegian Krone',
  'NZD':'New Zealand Dollar',
  'PHP':'Philippine Peso',
  'PLN':'Polish Zloty',
  'RON':'Romanian Leu',
  'RUB':'Russian Ruble',
  'SAR':'Saudi Riyal',
  'SEK':'Swedish Krona',
  'SGD':'Singapore Dollar',
  'THB':'Thai Baht',
  'TWD':'New Taiwan Dollar',
  'USD':'US Dollar',
  'VND':'Vietnamese Dong',
  'ZAR':'South African Ran',
};